config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index new create show update destroy edit] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
# The comment of a bookmark cannot be shorter than 6 characters.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, dependent: :destroy, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

# A list must have a unique name.

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, dependent: :destroy, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

# A movie must have a unique title and an overview.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new # not saved yet!
  end

  def create #ETAPE 2 réception des data du form
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(list_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :see_other
    end
  end

  def list_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new # not saved yet!
  end

  def create #ETAPE 2 réception des data du form
    @list = List.new(list_params)
    @list.save

    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    # raise
    # @movies = @list.movies
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/premium-vector/now-showing-movie-cinema-poster-banner-background_7102-277.jpg?w=2000);">
  <div class="container">
    <h1><strong>Lists:</strong></h1>
    <p>THE WAGON CINESHOW</p>
    <div class="btn btn-ghost">
      <%= link_to "Add a new list", new_list_path(@list) %>
    </div>
  </div>
</div>

<%# <p>Find me in app/views/lists/index.html.erb</p> %>

<div class="cards">
  <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key %>)">
      <div class="link">
        <%= link_to list.name, list_path(list) %>
      </div>
     </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key %>);">
<p><strong><%= @list.name %> Movies</strong></p>
</div>
<ul class="list-group">
  <% @list.movies.each do |movie| %>
    <li class="list-group-item"><%= movie.title %> | <%= movie.overview %> | <%= movie.rating %> <%= link_to "🗑", lists_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
  <% end %>
</ul>

<%= link_to "Add a Bookmark", new_list_bookmark_path(@list, @bookmark) %>